ls:
  .dir: kebab-case
  .vue: kebab-case
  .js: kebab-case
  .html: kebab-case
  .css: kebab-case
  .png: kebab-case

ignore:
  - .git
  - node_modules
  - src/public/webpack.config.js
  - src/public/app/lib
