apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-storage
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
        tier: mongoDB
    spec:
      containers:
        - name: mongodb
          image: mongodb:4.0
          ports:
            - containerPort: 27017
              name: mongodb
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: mongodb
              mountPath: /var/lib/mongodb/data
              subPath: data
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 5432
  selector:
    app: mongodb
    tier: mongoDB
