// GenEvo
// Copyright (C) 2019 Institut Pasteur
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

// =========================================================================
// Ignore data fields not used by the interface
// =========================================================================

module.exports = {
  _id: 0,
  'Body#Adult_brain_(microarray)': 0,
  'Body#Blood': 0,
  'Body#Brain_(MS)': 0,
  'Body#Brain_(RNAseq)': 0,
  'Body#Fetal_brain_(microarray)': 0,
  'Body#Heart': 0,
  'Body#Kidney': 0,
  'Body#Liver': 0,
  'Body#Lung': 0,
  'Body#Ovary': 0,
  'Body#Skeletal_muscle': 0,
  'Body#Testes': 0,
  'Brain_Cells#Human-Cortex_Astrocyte': 0,
  'Brain_Cells#Human-Cortex_Choroid': 0,
  'Brain_Cells#Human-Cortex_EN-PFC1': 0,
  'Brain_Cells#Human-Cortex_EN-PFC2': 0,
  'Brain_Cells#Human-Cortex_EN-PFC3': 0,
  'Brain_Cells#Human-Cortex_EN-V1-1': 0,
  'Brain_Cells#Human-Cortex_EN-V1-2': 0,
  'Brain_Cells#Human-Cortex_EN-V1-3': 0,
  'Brain_Cells#Human-Cortex_Endothelial': 0,
  'Brain_Cells#Human-Cortex_Glyc': 0,
  'Brain_Cells#Human-Cortex_IN-CTX-CGE1': 0,
  'Brain_Cells#Human-Cortex_IN-CTX-CGE2': 0,
  'Brain_Cells#Human-Cortex_IN-CTX-MGE1': 0,
  'Brain_Cells#Human-Cortex_IN-CTX-MGE2': 0,
  'Brain_Cells#Human-Cortex_IN-STR': 0,
  'Brain_Cells#Human-Cortex_IPC-div1': 0,
  'Brain_Cells#Human-Cortex_IPC-div2': 0,
  'Brain_Cells#Human-Cortex_IPC-nEN1': 0,
  'Brain_Cells#Human-Cortex_IPC-nEN2': 0,
  'Brain_Cells#Human-Cortex_IPC-nEN3': 0,
  'Brain_Cells#Human-Cortex_MGE-IPC1': 0,
  'Brain_Cells#Human-Cortex_MGE-IPC2': 0,
  'Brain_Cells#Human-Cortex_MGE-IPC3': 0,
  'Brain_Cells#Human-Cortex_MGE-RG1': 0,
  'Brain_Cells#Human-Cortex_MGE-RG2': 0,
  'Brain_Cells#Human-Cortex_MGE-div': 0,
  'Brain_Cells#Human-Cortex_Microglia': 0,
  'Brain_Cells#Human-Cortex_Mural': 0,
  'Brain_Cells#Human-Cortex_OPC': 0,
  'Brain_Cells#Human-Cortex_RG-div1': 0,
  'Brain_Cells#Human-Cortex_RG-div2': 0,
  'Brain_Cells#Human-Cortex_RG-early': 0,
  'Brain_Cells#Human-Cortex_nEN-early1': 0,
  'Brain_Cells#Human-Cortex_nEN-early2': 0,
  'Brain_Cells#Human-Cortex_nEN-late': 0,
  'Brain_Cells#Human-Cortex_nIN1': 0,
  'Brain_Cells#Human-Cortex_nIN2': 0,
  'Brain_Cells#Human-Cortex_nIN3': 0,
  'Brain_Cells#Human-Cortex_nIN4': 0,
  'Brain_Cells#Human-Cortex_nIN5': 0,
  'Brain_Cells#Human-Cortex_oRG': 0,
  'Brain_Cells#Human-Cortex_tRG': 0,
  'Brain_Cells#Human-Cortex_vRG': 0,
  'Brain_Cells#Mouse-Cerebellum_Astrocytes': 0,
  'Brain_Cells#Mouse-Cerebellum_Blood vessel': 0,
  'Brain_Cells#Mouse-Cerebellum_Ciliated cells': 0,
  'Brain_Cells#Mouse-Cerebellum_Erythrocyte': 0,
  'Brain_Cells#Mouse-Cerebellum_GABA Progenitor': 0,
  'Brain_Cells#Mouse-Cerebellum_GABAergic Interneuron': 0,
  'Brain_Cells#Mouse-Cerebellum_Glia': 0,
  'Brain_Cells#Mouse-Cerebellum_Glutamatergic DCN': 0,
  'Brain_Cells#Mouse-Cerebellum_Granule': 0,
  'Brain_Cells#Mouse-Cerebellum_Meninges/Pia membrane': 0,
  'Brain_Cells#Mouse-Cerebellum_Microglia': 0,
  'Brain_Cells#Mouse-Cerebellum_Midbrain': 0,
  'Brain_Cells#Mouse-Cerebellum_Progenitor': 0,
  'Brain_Cells#Mouse-Cerebellum_Purkinje': 0,
  'Brain_Cells#Mouse-Cerebellum_Roof plate': 0,
  'Brain_Diseases#Blindness': 0,
  'Brain_Diseases#DBD': 0,
  'Brain_Diseases#Deafness': 0,
  'Brain_Diseases#Depression': 0,
  'Brain_Diseases#Dyslexia': 0,
  'Brain_Diseases#Encephalopathy': 0,
  'Brain_Diseases#Epilepsy': 0,
  'Brain_Diseases#Headache': 0,
  'Brain_Diseases#Huntington': 0,
  'Brain_Diseases#Intellectual_disability': 0,
  'Brain_Diseases#Macrocephaly': 0,
  'Brain_Diseases#Microcephaly': 0,
  'Brain_Diseases#Myelin': 0,
  'Brain_Diseases#Neurodegeneration': 0,
  'Brain_Diseases#Parkinson': 0,
  'Brain_Diseases#SFARI': 0,
  'Brain_Diseases#Schizophrenia': 0,
  'Brain_Diseases#TADA': 0,
  'Brain_Functions#Cell_adhesion_and_trans-synaptic_signaling': 0,
  'Brain_Functions#Cell_metabolism': 0,
  'Brain_Functions#Cholinergic': 0,
  'Brain_Functions#Dopaminergic': 0,
  'Brain_Functions#Endocytosis': 0,
  'Brain_Functions#Excitability': 0,
  'Brain_Functions#Excitatory_(MS)': 0,
  'Brain_Functions#Exocytosis': 0,
  'Brain_Functions#G-protein-coupled_receptor_signaling': 0,
  'Brain_Functions#G-protein_relay': 0,
  'Brain_Functions#GABAergic': 0,
  'Brain_Functions#Glutamatergic': 0,
  'Brain_Functions#Inhibitory_(MS)': 0,
  'Brain_Functions#Intracellular_signal_transduction': 0,
  'Brain_Functions#Intracellular_trafficking': 0,
  'Brain_Functions#Ion_balance/transport': 0,
  'Brain_Functions#Ligand-gated_ion_channel_signaling': 0,
  'Brain_Functions#Neurotransmitter_metabolism': 0,
  'Brain_Functions#Peptide/neurotrophin_signals': 0,
  'Brain_Functions#Protein_cluster': 0,
  'Brain_Functions#RNA_and_protein_synthesis_folding_and_breakdown': 0,
  'Brain_Functions#Serotonergic': 0,
  'Brain_Functions#Structural_plasticity': 0,
  'Brain_Functions#Tyrosine_kinase_signaling': 0,
  'Brain_Structures#Adrenal_cortex': 0,
  'Brain_Structures#Adrenal_gland': 0,
  'Brain_Structures#Amygdala': 0,
  'Brain_Structures#Caudate_nucleus': 0,
  'Brain_Structures#Cerebellum': 0,
  'Brain_Structures#Cerebellum_peduncles': 0,
  'Brain_Structures#Ciliary_ganglion': 0,
  'Brain_Structures#Cingulate_cortex': 0,
  'Brain_Structures#Dorsal_root_ganglion': 0,
  'Brain_Structures#Globus_pallidus': 0,
  'Brain_Structures#Hypothalamus': 0,
  'Brain_Structures#Medulla_oblongata': 0,
  'Brain_Structures#Occipital_lobe': 0,
  'Brain_Structures#Olfactory_bulb': 0,
  'Brain_Structures#Parietal_lobe': 0,
  'Brain_Structures#Pineal_gland_(day)': 0,
  'Brain_Structures#Pineal_gland_(night)': 0,
  'Brain_Structures#Pons': 0,
  'Brain_Structures#Prefrontal_cortex': 0,
  'Brain_Structures#Retina': 0,
  'Brain_Structures#Spinal_cord': 0,
  'Brain_Structures#Subthalamic_nucleus': 0,
  'Brain_Structures#Superior_cervical_ganglion': 0,
  'Brain_Structures#Temporal_lobe': 0,
  'Brain_Structures#Thalamus': 0,
  'Brain_Structures#Trigeminal_ganglion': 0,
  'Evolution#Brain_diseases_negative': 0,
  'Evolution#Brain_diseases_neutral': 0,
  'Evolution#Brain_diseases_positive': 0,
  'Evolution#Brain_functions_negative': 0,
  'Evolution#Brain_functions_neutral': 0,
  'Evolution#Brain_functions_positive': 0,
  'Evolution#Brain_structures-functions-diseases_negative': 0,
  'Evolution#Brain_structures-functions-diseases_neutral': 0,
  'Evolution#Brain_structures-functions-diseases_positive': 0,
  'Evolution#Brain_structures_negative': 0,
  'Evolution#Brain_structures_neutral': 0,
  'Evolution#Brain_structures_positive': 0,
  'Evolution#High_CADD': 0,
  'Evolution#High_introgression': 0,
  'Evolution#Low_introgression': 0,
  'Evolution#Negative': 0,
  'Evolution#Neutral': 0,
  'Evolution#No_introgression': 0,
  'Evolution#Positive': 0
}
